fix: refactor config
Open-Attestation/open-attestation-cli pull request #178
Opened 2021-12-14 08:27 UTC by simboonlong

2021-12-14 09:29 UTC, isaackps requested changes

2021-12-14 09:29 UTC, isaackps commented on src/implementations/config/create.ts
> -    );
need revert back

2021-12-15 08:32 UTC, simboonlong commented on src/implementations/config/create.ts
> -    );
reverted back validate test

2021-12-15 09:02 UTC, isaackps commented on src/commands/config/create.ts
> +  withNetworkAndWalletSignerOption(
can revert back to withWalletOption

2021-12-16 00:57 UTC, simboonlong commented on src/implementations/config/types.ts
> +type Wallet = WalletEncrypted | WalletAwsKms;
yeah ok

2021-12-16 00:57 UTC, simboonlong commented on src/commands/config/create.ts
> +  withNetworkAndWalletSignerOption(
ok

2021-12-16 02:04 UTC, isaackps commented on src/implementations/config/create.ts
> +  let dnsNameDid: string | undefined = "";
in this case since its an empty string already do we need the undefined?

2021-12-16 03:53 UTC, isaackps approved these changes

2021-12-16 03:56 UTC, merged

2021-12-16 04:01 UTC, john-dot-oa commented
:tada: This PR is included in version 1.45.8 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@govtechsg/open-attestation-cli/v/1.45.8)
- [GitHub release](https://github.com/Open-Attestation/open-attestation-cli/releases/tag/v1.45.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: